### ISSUE TITLE
Newest version at PyPi

### ISSUE THREAD

**Issue by Schwankenson** [dellis23/django-wordpress-auth#5]
Hello,

great app, I can connect the flexibility of django with the huge plugin base ofWordpress, and avoid coding things in PHP. Thank you!

When is the next PyPi version planned? I installed it with pip and had some problems with Python 3.4. Now I installed it with pip from the repository, and everythings works. But I would like to avoid github links in my requirements.txt pip file.

Cheers,

Johannes

**Comment by dellis23** [comment]
Thanks for the heads up.  I'll get on this asap.

**Comment by dellis23** [comment]
@Schwankenson I'm not seeing any actual changes in the code between what's in PyPI and what's here, other than the addition of the github URL to the project.  You wouldn't happen to know why the PyPI version caused issues whereas this version did not, would you?

**Comment by dellis23** [comment]
@mstrcnvs Is there a way on PyPI you can add my account to also have access to push / update the package?  I'm getting a 403 unauthorized at the moment.  My username on there is `daniel.ellis`.

**Comment by rafaelcanovas** [comment]
Full access granted :)
Don't forget to upload sdist as well as universal wheel format!

Cheers!

**Comment by Schwankenson** [comment]
@dellis23: When I install with pip ("pip install django-wordpress-auth",  tried pip version 1.5.6 and 6.1.1), for example the last line of models.py is

```
return phpserialize.loads(opt)
```

and I get the error

```
TypeError: 'str' does not support the buffer interface
```

 and request.wordpress_user is boolean false.

When I install it with the following line in my requirements file

```
-e git://github.com/dellis23/django-wordpress-auth.git@a4aad99a6dced43c052e19d39bb91c2ed7885c5a#egg=django-wordpress-auth
```

the last line is 

```
return phpserialize.loads(force_bytes(opt), decode_strings=True)
```

and everything works.

**Comment by dellis23** [comment]
Yup, looks like you're right.  A version bump and republish should do the trick.

**Comment by rafaelcanovas** [comment]
My bad guys, corrected a few compatibility issues with Python 3 but hasn't published a new version. Are you doing it @dellis23 or you want me to do it?

**Comment by dellis23** [comment]
@mstrcnvs If you're familiar with the sdist and wheel format stuff feel free, and it would be appreciated :-)

**Comment by rafaelcanovas** [comment]
Done guys. Could upload the sdist, but for some reason I can't upload the wheel format, it's giving me "Unsupported platform" on PyPI. But it's there, released :)

**Comment by dellis23** [comment]
@mstrcnvs Thank you!

**Comment by rafaelcanovas** [comment]
Drafted a new release called v0.1.31 so then I could upload both sdist and wheel formats.

**Comment by Schwankenson** [comment]
I´m sorry to reopen this, but I still have to install django-wordpress auth with 

```
pip install git+https://github.com/dellis23/django-wordpress-auth#f45f57aeaa16b48f1916c3af7ea32873fbb0aaa9
```

When I just enter 

```
pip install django-wordpress-auth
```

, I still get this python3 incompatible error

**Comment by rafaelcanovas** [comment]
@Schwankenson, what's the output of the command `pip freeze`?

**Comment by Schwankenson** [comment]
It`s django-wordpress-auth==0.1.31

**Comment by Schwankenson** [comment]
Hey mstrcnvs, I sorry to tell you, that the problem persists...

**Comment by rafaelcanovas** [comment]
@Schwankenson, please paste the complete error traceback.

**Comment by Schwankenson** [comment]
I can post the error traceback later, but it is not important for this: 
As described above: When I install django wordpress auth with `pip install django-wordpress-auth==0.1.31`, than I have not the newest version of models.py, where the last line is:

`return phpserialize.loads(force_bytes(opt), decode_strings=True)`

but the version https://github.com/dellis23/django-wordpress-auth/blob/38e2366a96d99e2cb449f2f43456e260c20eebf7/wordpress_auth/models.py

`return phpserialize.loads(opt)`

And this version if before your commit "Normalization of bytes and str types between Python 2 and 3", and causes errors in Python 3.4.

It`s a problem with the python package index, not with your code.

When I execute `pip freeze`, than 
'django-wordpress-auth==0.1.31'
is shown

**Comment by rafaelcanovas** [comment]
Well, if I download directly from PyPI I get the latest version (0.1.31) correctly.

Try to run:

``` sh
pip install django-wordpress-auth -U --force-reinstall
```

See if that works. If it doesn't don't know what to tell you :'(
